#!/bin/sh

while read file
do 
  case "$1" in
    "d") mv "$file" ~/.local/trash ;;
    "w") setbg "$file" ;;
    "u") uploadfile "$file" ;;
    "x") mv "$file" ~/pix/wall/old-collection/ ;;
  esac
done
