#!/bin/sh

while read file
do 
  case "$1" in
    "d") mv "$file" ~/.local/trash ;;
    "w") setbg "$file" ;;
    "u") uploadfile "$file" ;;
    "x") mv "$file" ~/pix/wall/old-collection/ ;;
    "c") mkdir -p /home/ahwx/temp-sxiv; cp "$file" /home/ahwx/temp-sxiv/ ;;
  esac
done
