#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
sudo yabai --load-sa

# SketchyBar settings
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# label spaces
yabai -m space 1 --label main
yabai -m space 2 --label terminal
yabai -m space 3 --label misc0
yabai -m space 4 --label misc1
yabai -m space 5 --label misc2
yabai -m space 6 --label chat
yabai -m space 7 --label notes
yabai -m space 8 --label matrix
yabai -m space 9 --label music
yabai -m space 10 --label mail


yabai -m config external_bar               all:35:0     \
                window_border              on           \
                focus_follows_mouse        autofocus    \
                mouse_follows_focus        on           \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.3          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.7          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         on           \
                window_animation_duration  0.3          \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             alt          \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                20           \
                bottom_padding             8            \
                left_padding               8            \
                right_padding              8            \
                window_gap                 12

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Settings|Calculator|System Preferences|System Settings|Software Update|Archive Utility|Finder)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Gimp$" title="Select file to save to" manage=off
yabai -m rule --add label="^Kdenlive$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
