#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#!/usr/bin/env sh

# bar settings
yabai -m config top_padding 20

# label spaces
yabai -m space 1 --label main
yabai -m space 2 --label terminal
yabai -m space 3 --label misc0
yabai -m space 4 --label misc1
yabai -m space 5 --label misc2
yabai -m space 6 --label chat
yabai -m space 7 --label notes
yabai -m space 8 --label matrix
yabai -m space 9 --label music
yabai -m space 10 --label mail

# window spawn rules

# Space 1
# yabai -m rule --add app="^Chromium$" space=main
# Space 6
# yabai -m rule --add app="^Messages$" space=chat
# yabai -m rule --add app="^Signal$" space=chat
# Space 7
# yabai -m rule --add app="^Inkdrop$" space=notes
# yabai -m rule --add app="^Arc$" space=notes
# Space 8
# yabai -m rule --add app="^Element$" space=matrix
# yabai -m rule --add app="^Cinny$" space=matrix
# Space 9
# yabai -m rule --add app="^Spotify$" space=music
# Space 10
# yabai -m rule --add app="^Mail$" space=mail

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_topmost               on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 on

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# float system preferences
yabai -m rule --add app="^(Calculator|System Preferences|System Settings|Archive Utility|Finder)$" manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# general gap settings
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/set_padding.py"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded.."
