#! /bin/sh

# Restore wallpaper
wallpaper-pywal

pgrep -x sxhkd > /dev/null || sxhkd &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七' '八'
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           25
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

bspc rule -a qutebrowser desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a surf desktop='^3' follow=on focus=on
bspc rule -a thunar desktop='^4' follow=on focus=on

