#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc config border_width 2
bspc config window_gap 12

bspc config normal_border_color "#e5e9f0"
bspc config active_border_color "#ffcc33"
bspc config focused_border_color "#2492e0"
bspc config presel_feedback_color "#b48ead"
bspc config urgent_border_color "#ff4040"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
